### ISSUE TITLE
could we get a port to newer versions?

### ISSUE THREAD

**Issue by Lowtrixx** [StevenDoesStuffs/RefinedCrafterProxy#2]
what would be needed to port to a newer version?

**Comment by StevenDoesStuffs** [comment]
I'll start looking into it in a few weeks but I assume not much since the mod is fairly small and already uses mojangs mappings.

**Comment by StevenDoesStuffs** [comment]
Finally got around to it! I'll test it tomorrow to make sure everything works then push a new release.

**Comment by StevenDoesStuffs** [comment]
Just uploaded it to curseforge, pending review now.

**Comment by StevenDoesStuffs** [comment]
It's in! Updated for: 1.18.2, 1.19.2, 1.20.1, 1.20.4.
